#!/bin/bash

#This find command allowes me to search for any /var/log files that have been modifyed in the last 7 days
find /var/log -type f -mtime +7




echo "                                                                                                                  "
sudo find / -type f -name ".*" -mtime +7
echo "                                                                                                            "


#This find command allowes me to search for any /etc/ files that have been modifyed in the last 7 days
find /etc/ -type f -mtime +7

